server:
    port: 8081
spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
endpoints:
  health:
    show-details: always

greeting-service:
    greeting: "Hola"
    default-value: "Word"
